In [13]:
import argparse, pdb
import numpy as np, tensorflow as tf
from utils import IMG_SIZE, LABELS, image_generator


def classify(model, test_dir):
    """
    Classifies all images in test_dir
    :param model: Model to be evaluated
    :param test_dir: Directory including the images
    :return: None
    """
    test_img_gen = image_generator.flow_from_directory(
        test_dir,
        target_size=(IMG_SIZE, IMG_SIZE),
        classes=LABELS,
        batch_size=1,
        shuffle=False,
    )

    ######### Your code starts here #########
    # Classify all images in the given folder
    # Calculate the accuracy and the number of test samples in the folder
    # test_img_gen has a list attribute filenames where you can access the
    # filename of the datapoint
        # break after 1 epoch
                #pdb.set_trace()
            
    num_test = test_img_gen.samples
    correct_results = 0
    for i in range(num_test):
        x_i, y_i = next(test_img_gen)
        pred = model(x_i)
        if (np.argmax(pred)!=np.argmax(y_i)):
            print(f'img: {i}')
            print(y_i)
            print(pred)
        else:
            correct_results+=1
    accuracy = float(correct_results/num_test)

    
    ######### Your code ends here #########

    print(f"Evaluated on {num_test} samples.")
    print(f"Accuracy: {accuracy*100:.0f}%")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--test_image_dir", type=str, default="datasets/test/")
    FLAGS, _ = parser.parse_known_args()
    model = tf.keras.models.load_model("./trained_models/trained.h5")
    #classify(model, FLAGS.test_image_dir)
    classify(model, 'datasets/test')

Found 150 images belonging to 3 classes.
img: 30
[[1. 0. 0.]]
tf.Tensor([[0.11753163 0.73148775 0.15098056]], shape=(1, 3), dtype=float32)
img: 59
[[0. 1. 0.]]
tf.Tensor([[0.3826277  0.03324359 0.5841287 ]], shape=(1, 3), dtype=float32)
img: 66
[[0. 1. 0.]]
tf.Tensor([[0.01528063 0.19646102 0.7882584 ]], shape=(1, 3), dtype=float32)
img: 72
[[0. 1. 0.]]
tf.Tensor([[0.00788159 0.07287961 0.91923875]], shape=(1, 3), dtype=float32)
img: 75
[[0. 1. 0.]]
tf.Tensor([[0.00184049 0.05164747 0.94651204]], shape=(1, 3), dtype=float32)
img: 81
[[0. 1. 0.]]
tf.Tensor([[0.01154882 0.40572202 0.58272916]], shape=(1, 3), dtype=float32)
img: 84
[[0. 1. 0.]]
tf.Tensor([[1.3990964e-04 3.5016787e-01 6.4969224e-01]], shape=(1, 3), dtype=float32)
img: 97
[[0. 1. 0.]]
tf.Tensor([[0.677212   0.17067882 0.15210922]], shape=(1, 3), dtype=float32)
img: 102
[[0. 0. 1.]]
tf.Tensor([[0.02324147 0.71379614 0.26296243]], shape=(1, 3), dtype=float32)
img: 110
[[0. 0. 1.]]
tf.Tensor([[0.08225576 0.6171703  0.300574  ]