In [11]:
import argparse, pdb
import numpy as np, tensorflow as tf
from utils import IMG_SIZE, LABELS, image_generator


def classify(model, test_dir):
    """
    Classifies all images in test_dir
    :param model: Model to be evaluated
    :param test_dir: Directory including the images
    :return: None
    """
    test_img_gen = image_generator.flow_from_directory(
        test_dir,
        target_size=(IMG_SIZE, IMG_SIZE),
        classes=LABELS,
        batch_size=1,
        shuffle=False,
    )

    ######### Your code starts here #########
    # Classify all images in the given folder
    # Calculate the accuracy and the number of test samples in the folder
    # test_img_gen has a list attribute filenames where you can access the
    # filename of the datapoint
        # break after 1 epoch
                #pdb.set_trace()
            
    num_test = test_img_gen.samples
    correct_results = 0
    for i in range(num_test):
        x_i, y_i = next(test_img_gen)
        pred = model(x_i)
        if (np.argmax(pred)!=np.argmax(y_i)):
            print(f'img: {i}')
            print(y_i)
            print(pred)
        else:
            correct_results+=1
    accuracy = float(correct_results/num_test)

    
    ######### Your code ends here #########

    print(f"Evaluated on {num_test} samples.")
    print(f"Accuracy: {accuracy*100:.0f}%")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--test_image_dir", type=str, default="datasets/test/")
    FLAGS, _ = parser.parse_known_args()
    model = tf.keras.models.load_model("./trained_models/trained.h5")
    #classify(model, FLAGS.test_image_dir)
    classify(model, 'datasets/test')

Found 150 images belonging to 3 classes.
img: 30
[[1. 0. 0.]]
tf.Tensor([[0.05370024 0.7999497  0.14635004]], shape=(1, 3), dtype=float32)
img: 59
[[0. 1. 0.]]
tf.Tensor([[0.1696084  0.03149796 0.7988936 ]], shape=(1, 3), dtype=float32)
img: 66
[[0. 1. 0.]]
tf.Tensor([[0.02251349 0.22862469 0.74886185]], shape=(1, 3), dtype=float32)
img: 72
[[0. 1. 0.]]
tf.Tensor([[0.02317126 0.16055033 0.8162784 ]], shape=(1, 3), dtype=float32)
img: 75
[[0. 1. 0.]]
tf.Tensor([[0.00208679 0.06556392 0.9323493 ]], shape=(1, 3), dtype=float32)
img: 84
[[0. 1. 0.]]
tf.Tensor([[2.4204761e-04 4.4154233e-01 5.5821568e-01]], shape=(1, 3), dtype=float32)
img: 97
[[0. 1. 0.]]
tf.Tensor([[0.5388415  0.24319197 0.21796654]], shape=(1, 3), dtype=float32)
img: 102
[[0. 0. 1.]]
tf.Tensor([[0.02031272 0.73218626 0.24750108]], shape=(1, 3), dtype=float32)
img: 110
[[0. 0. 1.]]
tf.Tensor([[0.03174963 0.5841767  0.38407376]], shape=(1, 3), dtype=float32)
img: 122
[[0. 0. 1.]]
tf.Tensor([[0.01028991 0.56914276 0.42056727