In [6]:
import argparse, pdb
import numpy as np, tensorflow as tf
from utils import IMG_SIZE, LABELS, image_generator


def classify(model, test_dir):
    """
    Classifies all images in test_dir
    :param model: Model to be evaluated
    :param test_dir: Directory including the images
    :return: None
    """
    test_img_gen = image_generator.flow_from_directory(
        test_dir,
        target_size=(IMG_SIZE, IMG_SIZE),
        classes=LABELS,
        batch_size=1,
        shuffle=False,
    )

    ######### Your code starts here #########
    # Classify all images in the given folder
    # Calculate the accuracy and the number of test samples in the folder
    # test_img_gen has a list attribute filenames where you can access the
    # filename of the datapoint
        # break after 1 epoch
                #pdb.set_trace()
            
    num_test = test_img_gen.samples
    correct_results = 0
    for i in range(num_test):
        x_i, y_i = next(test_img_gen)
        pred = model(x_i)
        if (np.argmax(pred)!=np.argmax(y_i)):
            print(f'img: {i}')
            print(y_i)
            print(pred)
        else:
            correct_results+=1
    accuracy = float(correct_results/num_test)

    
    ######### Your code ends here #########

    print(f"Evaluated on {num_test} samples.")
    print(f"Accuracy: {accuracy*100:.0f}%")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--test_image_dir", type=str, default="datasets/test/")
    FLAGS, _ = parser.parse_known_args()
    model = tf.keras.models.load_model("./trained_models/trained.h5")
    #classify(model, FLAGS.test_image_dir)
    classify(model, 'datasets/test')



Found 150 images belonging to 3 classes.
img: 30
[[1. 0. 0.]]
tf.Tensor([[0.11064778 0.7456545  0.14369772]], shape=(1, 3), dtype=float32)
img: 59
[[0. 1. 0.]]
tf.Tensor([[0.08848566 0.04077286 0.8707414 ]], shape=(1, 3), dtype=float32)
img: 66
[[0. 1. 0.]]
tf.Tensor([[0.01206491 0.20032841 0.78760666]], shape=(1, 3), dtype=float32)
img: 72
[[0. 1. 0.]]
tf.Tensor([[0.013165   0.07367869 0.9131563 ]], shape=(1, 3), dtype=float32)
img: 75
[[0. 1. 0.]]
tf.Tensor([[0.001566   0.04032571 0.9581083 ]], shape=(1, 3), dtype=float32)
img: 81
[[0. 1. 0.]]
tf.Tensor([[0.00816796 0.26480743 0.7270246 ]], shape=(1, 3), dtype=float32)
img: 97
[[0. 1. 0.]]
tf.Tensor([[0.5629081  0.18169631 0.25539562]], shape=(1, 3), dtype=float32)
img: 102
[[0. 0. 1.]]
tf.Tensor([[0.03279139 0.7515867  0.21562192]], shape=(1, 3), dtype=float32)
img: 110
[[0. 0. 1.]]
tf.Tensor([[0.02892025 0.7044315  0.26664826]], shape=(1, 3), dtype=float32)
img: 122
[[0. 0. 1.]]
tf.Tensor([[0.0298483  0.58992404 0.38022766]], shape