In [4]:
import argparse, pdb
import numpy as np, tensorflow as tf
from utils import IMG_SIZE, LABELS, image_generator


def classify(model, test_dir):
    """
    Classifies all images in test_dir
    :param model: Model to be evaluated
    :param test_dir: Directory including the images
    :return: None
    """
    test_img_gen = image_generator.flow_from_directory(
        test_dir,
        target_size=(IMG_SIZE, IMG_SIZE),
        classes=LABELS,
        batch_size=1,
        shuffle=False,
    )

    ######### Your code starts here #########
    # Classify all images in the given folder
    # Calculate the accuracy and the number of test samples in the folder
    # test_img_gen has a list attribute filenames where you can access the
    # filename of the datapoint
        # break after 1 epoch
                #pdb.set_trace()
    import matplotlib.pyplot as plt
    num_test = test_img_gen.samples
    correct_results = 0
    for i in range(num_test):
        x_i, y_i = next(test_img_gen)
        pred = model(x_i)
        if (np.argmax(pred)!=np.argmax(y_i)):
            print(f'img: {i}')
            print(y_i)
            print(pred)
        else:
            correct_results+=1
    accuracy = float(correct_results/num_test)

    
    ######### Your code ends here #########

    print(f"Evaluated on {num_test} samples.")
    print(f"Accuracy: {accuracy*100:.0f}%")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--test_image_dir", type=str, default="datasets/test/")
    FLAGS, _ = parser.parse_known_args()
    model = tf.keras.models.load_model("./trained_models/trained.h5")
    #classify(model, FLAGS.test_image_dir)
    classify(model, 'datasets/test')

Found 150 images belonging to 3 classes.
[[1. 0. 0.]]
tf.Tensor([[0.10720269 0.71143514 0.18136221]], shape=(1, 3), dtype=float32)
[[1. 0. 0.]]
tf.Tensor([[0.28633463 0.67092186 0.04274355]], shape=(1, 3), dtype=float32)
[[0. 1. 0.]]
tf.Tensor([[0.253612   0.01734961 0.72903836]], shape=(1, 3), dtype=float32)
[[0. 1. 0.]]
tf.Tensor([[0.01588929 0.26724294 0.71686774]], shape=(1, 3), dtype=float32)
[[0. 1. 0.]]
tf.Tensor([[0.01741703 0.06164416 0.92093885]], shape=(1, 3), dtype=float32)
[[0. 1. 0.]]
tf.Tensor([[0.0013423  0.0604838  0.93817395]], shape=(1, 3), dtype=float32)
[[0. 1. 0.]]
tf.Tensor([[0.00703882 0.2662685  0.7266927 ]], shape=(1, 3), dtype=float32)
[[0. 1. 0.]]
tf.Tensor([[0.48417097 0.31296602 0.20286301]], shape=(1, 3), dtype=float32)
[[0. 0. 1.]]
tf.Tensor([[0.01454114 0.85991347 0.12554549]], shape=(1, 3), dtype=float32)
[[0. 0. 1.]]
tf.Tensor([[0.062718   0.56838703 0.368895  ]], shape=(1, 3), dtype=float32)
[[0. 0. 1.]]
tf.Tensor([[0.02353701 0.7159899  0.2604731 ]]

<Figure size 432x288 with 0 Axes>

<Figure size 432x288 with 0 Axes>

<Figure size 432x288 with 0 Axes>

<Figure size 432x288 with 0 Axes>

<Figure size 432x288 with 0 Axes>

<Figure size 432x288 with 0 Axes>

<Figure size 432x288 with 0 Axes>

<Figure size 432x288 with 0 Axes>

<Figure size 432x288 with 0 Axes>

<Figure size 432x288 with 0 Axes>

<Figure size 432x288 with 0 Axes>

<Figure size 432x288 with 0 Axes>

<Figure size 432x288 with 0 Axes>

<Figure size 432x288 with 0 Axes>

<Figure size 432x288 with 0 Axes>