In [8]:
import argparse, pdb
import numpy as np, tensorflow as tf
from utils import IMG_SIZE, LABELS, image_generator


def classify(model, test_dir):
    """
    Classifies all images in test_dir
    :param model: Model to be evaluated
    :param test_dir: Directory including the images
    :return: None
    """
    test_img_gen = image_generator.flow_from_directory(
        test_dir,
        target_size=(IMG_SIZE, IMG_SIZE),
        classes=LABELS,
        batch_size=1,
        shuffle=False,
    )

    ######### Your code starts here #########
    # Classify all images in the given folder
    # Calculate the accuracy and the number of test samples in the folder
    # test_img_gen has a list attribute filenames where you can access the
    # filename of the datapoint
        # break after 1 epoch
                #pdb.set_trace()
            
    num_test = test_img_gen.samples
    correct_results = 0
    for i in range(num_test):
        x_i, y_i = next(test_img_gen)
        pred = model(x_i)
        if (np.argmax(pred)!=np.argmax(y_i)):
            print(f'img: {i}')
            print(y_i)
            print(pred)
        else:
            correct_results+=1
    accuracy = float(correct_results/num_test)

    
    ######### Your code ends here #########

    print(f"Evaluated on {num_test} samples.")
    print(f"Accuracy: {accuracy*100:.0f}%")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--test_image_dir", type=str, default="datasets/test/")
    FLAGS, _ = parser.parse_known_args()
    model = tf.keras.models.load_model("./trained_models/trained.h5")
    #classify(model, FLAGS.test_image_dir)
    classify(model, 'datasets/test')

Found 150 images belonging to 3 classes.
img: 30
[[1. 0. 0.]]
tf.Tensor([[0.07992243 0.8194729  0.10060472]], shape=(1, 3), dtype=float32)
img: 39
[[1. 0. 0.]]
tf.Tensor([[0.40260968 0.55464935 0.04274096]], shape=(1, 3), dtype=float32)
img: 59
[[0. 1. 0.]]
tf.Tensor([[0.31415242 0.03821969 0.64762783]], shape=(1, 3), dtype=float32)
img: 66
[[0. 1. 0.]]
tf.Tensor([[0.01441627 0.20725287 0.7783308 ]], shape=(1, 3), dtype=float32)
img: 72
[[0. 1. 0.]]
tf.Tensor([[0.0210796 0.0793272 0.8995931]], shape=(1, 3), dtype=float32)
img: 75
[[0. 1. 0.]]
tf.Tensor([[0.00117991 0.03770611 0.96111405]], shape=(1, 3), dtype=float32)
img: 81
[[0. 1. 0.]]
tf.Tensor([[0.00497527 0.4513511  0.54367363]], shape=(1, 3), dtype=float32)
img: 84
[[0. 1. 0.]]
tf.Tensor([[4.2850713e-04 4.1455996e-01 5.8501154e-01]], shape=(1, 3), dtype=float32)
img: 97
[[0. 1. 0.]]
tf.Tensor([[0.63526726 0.20068711 0.16404568]], shape=(1, 3), dtype=float32)
img: 102
[[0. 0. 1.]]
tf.Tensor([[0.02009316 0.60763156 0.37227535]], s